In [48]:
from array import *

In [49]:
MeuVetor = array('i', [1,2,3])

In [50]:
MeuVetor.pop()
MeuVetor

array('i', [1, 2])

In [51]:
MeuVetor.append(4)
MeuVetor

array('i', [1, 2, 4])

In [52]:
MeuVetor.pop(0)
MeuVetor

array('i', [2, 4])

In [53]:
lista = [7,8,9]
MeuVetor.fromlist(lista)
MeuVetor

array('i', [2, 4, 7, 8, 9])

In [54]:
OutroVetor = array("i", [4,5,6])
MeuVetor.extend(OutroVetor)
MeuVetor

array('i', [2, 4, 7, 8, 9, 4, 5, 6])

In [55]:
MeuVetor.reverse()
MeuVetor

array('i', [6, 5, 4, 9, 8, 7, 4, 2])

In [56]:
MeuVetor.count(2)

1

In [57]:
MeuVetor.index(9)

3

In [58]:
len(MeuVetor)

8

### Numpy

In [59]:
import numpy as np

In [60]:
a = np.array([3., 4., 5.])
a

array([ 3.,  4.,  5.])

In [62]:
type(a)

numpy.ndarray

#### Número de dimensões/eixos

In [67]:
b = np.array([[0, 1, 2], [3, 4,5]])
print(b)
print(b.ndim)

[[0 1 2]
 [3 4 5]]
2


In [79]:
def printinfo(b):
    print(b.shape)
    print(b.size)
    print(b.dtype)
printinfo(b)

(2, 3)
6
int64


In [80]:
c = np.arange(12).reshape(3, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
printinfo(c)

(3, 4)
12
int64


In [91]:
np.ones((3,3,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [124]:
td = np.random.rand(3,2)

In [125]:
td

array([[ 0.58391573,  0.09199836],
       [ 0.72370609,  0.91421394],
       [ 0.18002999,  0.10659972]])

In [134]:
vazio = np.empty((5,5))
vazio

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [145]:
np.full((2,3), 7)

array([[ 7.,  7.,  7.],
       [ 7.,  7.,  7.]])

In [147]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [149]:
np.linspace(0, 10, 2)

array([  0.,  10.])

In [165]:
a = np.arange(0, 30, 3.).reshape(5,2)
a

array([[  0.,   3.],
       [  6.,   9.],
       [ 12.,  15.],
       [ 18.,  21.],
       [ 24.,  27.]])

In [167]:
np.savetxt("saida.txt", a,  delimiter=",")

In [173]:
np.loadtxt("saida.txt", delimiter=",", unpack=True)

array([[  0.,   6.,  12.,  18.,  24.],
       [  3.,   9.,  15.,  21.,  27.]])